### PR TITLE
Upgrade Flutter, Isar and ObjectBox and remove Firestore executor

### PR DESCRIPTION
**Pull request by blaugold**
This PR migrates the app to Flutter 2.10.0.

It also removes the Firestore executor since it is not used and its dependencies increase build times on macOS/iOS a lot. If it should be resurected it is still in the Git history.

The Isar executor is migrated to the latest version. This does not include filling in the unimplemented methods.

The ObjectBox dependency is upgraded to the latest version.

### CODE REVIEW

**Comment by greenrobot-team** [comment]
Thanks, will have a look at this! First observation: the import stuff looks fishy, maybe there is a better solution.

**Comment by blaugold** [comment]
Turns out that with the prefix of the `objectbox` imports, the prefix for `isar` imports aren't necessary anymore.

**Review by robertaq1998 — COMMENTED** [review]
good

**Review by robertaq1998 — COMMENTED** [review]
.

**Comment by greenrobot-team** [comment]
Thanks again, merged and made some additional updates!

**Pull request merged**
